# Generated by Django 4.0 on 2023-12-11 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True, verbose_name='Nombre de categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre articulo')),
                ('codigo', models.CharField(max_length=60)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('punto_de_reorden', models.PositiveIntegerField(default=0)),
                ('categoria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.categoria')),
            ],
            options={
                'verbose_name': 'articulo',
                'verbose_name_plural': 'articulos',
                'ordering': ['nombre'],
            },
        ),
    ]
