# Generated by Django 4.0 on 2023-12-11 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True, verbose_name='Nombre Deposito')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('articulo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.articulo')),
                ('deposito_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.deposito')),
            ],
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='stock.articulo')),
            ],
        ),
    ]
