# Generated by Django 4.0 on 2023-12-12 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_deposito_stock_formula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='articulo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.articulo'),
        ),
    ]
