# Generated by Django 4.0 on 2023-12-12 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_formula_articulo_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='categoria_id',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='formula',
            old_name='articulo_id',
            new_name='articulo',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='articulo_id',
            new_name='articulo',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='deposito_id',
            new_name='deposito',
        ),
        migrations.AlterField(
            model_name='articulo',
            name='id',
            field=models.BigAutoField(db_column='ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='id',
            field=models.BigAutoField(db_column='ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='deposito',
            name='id',
            field=models.BigAutoField(db_column='ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='formula',
            name='id',
            field=models.BigAutoField(db_column='ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.BigAutoField(db_column='ID', primary_key=True, serialize=False),
        ),
    ]
